import { Component } from '@angular/core';

@Component({
  templateUrl: './icon-show.html',
  styleUrls: ['./icon.less'],
})
export class IconShowComponent {
  iconNames: Array<string> = [
    'refresh',
    'checkmark',
    'alert-warn-bg',
    'add1',
    'alert-prompt',
    'close',
    'info-circle',
    'warn',
    'exclamation-circle',
    'check-circle',
    'calendar',
    'angle-left',
    'angle-right',
    'config',
    'arrow-down',
    'arrow-right',
    'minus-square',
    'accordion-fold',
    'accordion-unfold',
    'search',
    'alert-success',
    'alert-warn',
    'location',
    'sort',
    'clear',
    'x-thin',
    'document',
    'file',
    'plus-square',
    'add',
    'reduce',
    'discount',
    'staricon',
    'alarm',
    'discount-sup',
    'slider-point',
    'filter',
    'sold-out',
    'delete',
    'sort-ascent',
    'sort-descent',
    'go-to-old-edition',
    'left-1',
    'left-2',
    'right-1',
    'right-2',
    'edit',
    'action-binding',
    'star',
    'cancel',
    'refresh-1',
    'time',
    'delete-1',
  ];
}